# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cyborg_controller/EmotionalFeedback.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EmotionalFeedback(genpy.Message):
  _md5sum = "6f61bf537c02522f197246d02ded0f2c"
  _type = "cyborg_controller/EmotionalFeedback"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 delta_pleasure # Changes in pleasure
float32 delta_arousal # Changes in arousal
float32 delta_dominance #Changes in dominance"""
  __slots__ = ['delta_pleasure','delta_arousal','delta_dominance']
  _slot_types = ['float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       delta_pleasure,delta_arousal,delta_dominance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EmotionalFeedback, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.delta_pleasure is None:
        self.delta_pleasure = 0.
      if self.delta_arousal is None:
        self.delta_arousal = 0.
      if self.delta_dominance is None:
        self.delta_dominance = 0.
    else:
      self.delta_pleasure = 0.
      self.delta_arousal = 0.
      self.delta_dominance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3f().pack(_x.delta_pleasure, _x.delta_arousal, _x.delta_dominance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.delta_pleasure, _x.delta_arousal, _x.delta_dominance,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3f().pack(_x.delta_pleasure, _x.delta_arousal, _x.delta_dominance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.delta_pleasure, _x.delta_arousal, _x.delta_dominance,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
