# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cyborg_controller/EmotionalState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EmotionalState(genpy.Message):
  _md5sum = "ff5f086e373f1e982e89fbc9298d99be"
  _type = "cyborg_controller/EmotionalState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string from_emotional_state
string to_emotional_state
float32 current_pleasure
float32 current_arousal
float32 current_dominance"""
  __slots__ = ['from_emotional_state','to_emotional_state','current_pleasure','current_arousal','current_dominance']
  _slot_types = ['string','string','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       from_emotional_state,to_emotional_state,current_pleasure,current_arousal,current_dominance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EmotionalState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.from_emotional_state is None:
        self.from_emotional_state = ''
      if self.to_emotional_state is None:
        self.to_emotional_state = ''
      if self.current_pleasure is None:
        self.current_pleasure = 0.
      if self.current_arousal is None:
        self.current_arousal = 0.
      if self.current_dominance is None:
        self.current_dominance = 0.
    else:
      self.from_emotional_state = ''
      self.to_emotional_state = ''
      self.current_pleasure = 0.
      self.current_arousal = 0.
      self.current_dominance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.from_emotional_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.to_emotional_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.current_pleasure, _x.current_arousal, _x.current_dominance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.from_emotional_state = str[start:end].decode('utf-8')
      else:
        self.from_emotional_state = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_emotional_state = str[start:end].decode('utf-8')
      else:
        self.to_emotional_state = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.current_pleasure, _x.current_arousal, _x.current_dominance,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.from_emotional_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.to_emotional_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.current_pleasure, _x.current_arousal, _x.current_dominance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.from_emotional_state = str[start:end].decode('utf-8')
      else:
        self.from_emotional_state = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_emotional_state = str[start:end].decode('utf-8')
      else:
        self.to_emotional_state = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.current_pleasure, _x.current_arousal, _x.current_dominance,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
