(cl:defpackage cyborg_controller-srv
  (:use )
  (:export
   "EMOTIONALSTATESERVICE"
   "<EMOTIONALSTATESERVICE-REQUEST>"
   "EMOTIONALSTATESERVICE-REQUEST"
   "<EMOTIONALSTATESERVICE-RESPONSE>"
   "EMOTIONALSTATESERVICE-RESPONSE"
  ))

