// Generated by gencpp from file rosarnl/JogPositionResult.msg
// DO NOT EDIT!


#ifndef ROSARNL_MESSAGE_JOGPOSITIONRESULT_H
#define ROSARNL_MESSAGE_JOGPOSITIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosarnl
{
template <class ContainerAllocator>
struct JogPositionResult_
{
  typedef JogPositionResult_<ContainerAllocator> Type;

  JogPositionResult_()
    {
    }
  JogPositionResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rosarnl::JogPositionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosarnl::JogPositionResult_<ContainerAllocator> const> ConstPtr;

}; // struct JogPositionResult_

typedef ::rosarnl::JogPositionResult_<std::allocator<void> > JogPositionResult;

typedef boost::shared_ptr< ::rosarnl::JogPositionResult > JogPositionResultPtr;
typedef boost::shared_ptr< ::rosarnl::JogPositionResult const> JogPositionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosarnl::JogPositionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosarnl::JogPositionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosarnl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'rosarnl': ['/home/lassegoncz/catkin_ws/src/ros-arnl/msg', '/home/lassegoncz/catkin_ws/devel/share/rosarnl/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosarnl::JogPositionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosarnl::JogPositionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosarnl::JogPositionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosarnl::JogPositionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosarnl::JogPositionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosarnl::JogPositionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosarnl::JogPositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rosarnl::JogPositionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rosarnl::JogPositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosarnl/JogPositionResult";
  }

  static const char* value(const ::rosarnl::JogPositionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosarnl::JogPositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# no value provided with result\n\
";
  }

  static const char* value(const ::rosarnl::JogPositionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosarnl::JogPositionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JogPositionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosarnl::JogPositionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rosarnl::JogPositionResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROSARNL_MESSAGE_JOGPOSITIONRESULT_H
