// Generated by gencpp from file rosarnl/JogPositionFeedback.msg
// DO NOT EDIT!


#ifndef ROSARNL_MESSAGE_JOGPOSITIONFEEDBACK_H
#define ROSARNL_MESSAGE_JOGPOSITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace rosarnl
{
template <class ContainerAllocator>
struct JogPositionFeedback_
{
  typedef JogPositionFeedback_<ContainerAllocator> Type;

  JogPositionFeedback_()
    : current()
    , duration()  {
    }
  JogPositionFeedback_(const ContainerAllocator& _alloc)
    : current(_alloc)
    , duration()  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _current_type;
  _current_type current;

   typedef ros::Duration _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::rosarnl::JogPositionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosarnl::JogPositionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct JogPositionFeedback_

typedef ::rosarnl::JogPositionFeedback_<std::allocator<void> > JogPositionFeedback;

typedef boost::shared_ptr< ::rosarnl::JogPositionFeedback > JogPositionFeedbackPtr;
typedef boost::shared_ptr< ::rosarnl::JogPositionFeedback const> JogPositionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosarnl::JogPositionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosarnl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'rosarnl': ['/home/lassegoncz/catkin_ws/src/ros-arnl/msg', '/home/lassegoncz/catkin_ws/devel/share/rosarnl/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosarnl::JogPositionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosarnl::JogPositionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosarnl::JogPositionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3028aaede1352c7007b717c9afed53f";
  }

  static const char* value(const ::rosarnl::JogPositionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3028aaede1352c7ULL;
  static const uint64_t static_value2 = 0x007b717c9afed53fULL;
};

template<class ContainerAllocator>
struct DataType< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosarnl/JogPositionFeedback";
  }

  static const char* value(const ::rosarnl::JogPositionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback, current pose and time since start of goal. TODO include remaining distannce\n\
geometry_msgs/Pose2D current\n\
duration duration\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::rosarnl::JogPositionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JogPositionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosarnl::JogPositionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosarnl::JogPositionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.current);
    s << indent << "duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSARNL_MESSAGE_JOGPOSITIONFEEDBACK_H
