// Generated by gencpp from file cyborg_controller/EmotionalStateServiceRequest.msg
// DO NOT EDIT!


#ifndef CYBORG_CONTROLLER_MESSAGE_EMOTIONALSTATESERVICEREQUEST_H
#define CYBORG_CONTROLLER_MESSAGE_EMOTIONALSTATESERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyborg_controller
{
template <class ContainerAllocator>
struct EmotionalStateServiceRequest_
{
  typedef EmotionalStateServiceRequest_<ContainerAllocator> Type;

  EmotionalStateServiceRequest_()
    : nothing()  {
    }
  EmotionalStateServiceRequest_(const ContainerAllocator& _alloc)
    : nothing(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nothing_type;
  _nothing_type nothing;





  typedef boost::shared_ptr< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EmotionalStateServiceRequest_

typedef ::cyborg_controller::EmotionalStateServiceRequest_<std::allocator<void> > EmotionalStateServiceRequest;

typedef boost::shared_ptr< ::cyborg_controller::EmotionalStateServiceRequest > EmotionalStateServiceRequestPtr;
typedef boost::shared_ptr< ::cyborg_controller::EmotionalStateServiceRequest const> EmotionalStateServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cyborg_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cyborg_controller': ['/home/lassegoncz/catkin_ws/src/cyborg_ros_controller/msg', '/home/lassegoncz/catkin_ws/devel/share/cyborg_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddfffbaa83f4c3ce761af512040042eb";
  }

  static const char* value(const ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddfffbaa83f4c3ceULL;
  static const uint64_t static_value2 = 0x761af512040042ebULL;
};

template<class ContainerAllocator>
struct DataType< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyborg_controller/EmotionalStateServiceRequest";
  }

  static const char* value(const ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nothing\n\
";
  }

  static const char* value(const ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nothing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmotionalStateServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyborg_controller::EmotionalStateServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "nothing: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nothing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBORG_CONTROLLER_MESSAGE_EMOTIONALSTATESERVICEREQUEST_H
