// Generated by gencpp from file cyborg_controller/EmotionalFeedback.msg
// DO NOT EDIT!


#ifndef CYBORG_CONTROLLER_MESSAGE_EMOTIONALFEEDBACK_H
#define CYBORG_CONTROLLER_MESSAGE_EMOTIONALFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyborg_controller
{
template <class ContainerAllocator>
struct EmotionalFeedback_
{
  typedef EmotionalFeedback_<ContainerAllocator> Type;

  EmotionalFeedback_()
    : delta_pleasure(0.0)
    , delta_arousal(0.0)
    , delta_dominance(0.0)  {
    }
  EmotionalFeedback_(const ContainerAllocator& _alloc)
    : delta_pleasure(0.0)
    , delta_arousal(0.0)
    , delta_dominance(0.0)  {
  (void)_alloc;
    }



   typedef float _delta_pleasure_type;
  _delta_pleasure_type delta_pleasure;

   typedef float _delta_arousal_type;
  _delta_arousal_type delta_arousal;

   typedef float _delta_dominance_type;
  _delta_dominance_type delta_dominance;





  typedef boost::shared_ptr< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct EmotionalFeedback_

typedef ::cyborg_controller::EmotionalFeedback_<std::allocator<void> > EmotionalFeedback;

typedef boost::shared_ptr< ::cyborg_controller::EmotionalFeedback > EmotionalFeedbackPtr;
typedef boost::shared_ptr< ::cyborg_controller::EmotionalFeedback const> EmotionalFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cyborg_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cyborg_controller': ['/home/lassegoncz/catkin_ws/src/cyborg_ros_controller/msg', '/home/lassegoncz/catkin_ws/devel/share/cyborg_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f61bf537c02522f197246d02ded0f2c";
  }

  static const char* value(const ::cyborg_controller::EmotionalFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f61bf537c02522fULL;
  static const uint64_t static_value2 = 0x197246d02ded0f2cULL;
};

template<class ContainerAllocator>
struct DataType< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyborg_controller/EmotionalFeedback";
  }

  static const char* value(const ::cyborg_controller::EmotionalFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 delta_pleasure # Changes in pleasure\n\
float32 delta_arousal # Changes in arousal\n\
float32 delta_dominance #Changes in dominance\n\
";
  }

  static const char* value(const ::cyborg_controller::EmotionalFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delta_pleasure);
      stream.next(m.delta_arousal);
      stream.next(m.delta_dominance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmotionalFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyborg_controller::EmotionalFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyborg_controller::EmotionalFeedback_<ContainerAllocator>& v)
  {
    s << indent << "delta_pleasure: ";
    Printer<float>::stream(s, indent + "  ", v.delta_pleasure);
    s << indent << "delta_arousal: ";
    Printer<float>::stream(s, indent + "  ", v.delta_arousal);
    s << indent << "delta_dominance: ";
    Printer<float>::stream(s, indent + "  ", v.delta_dominance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBORG_CONTROLLER_MESSAGE_EMOTIONALFEEDBACK_H
