// Generated by gencpp from file cyborg_controller/EmotionalState.msg
// DO NOT EDIT!


#ifndef CYBORG_CONTROLLER_MESSAGE_EMOTIONALSTATE_H
#define CYBORG_CONTROLLER_MESSAGE_EMOTIONALSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyborg_controller
{
template <class ContainerAllocator>
struct EmotionalState_
{
  typedef EmotionalState_<ContainerAllocator> Type;

  EmotionalState_()
    : from_emotional_state()
    , to_emotional_state()
    , current_pleasure(0.0)
    , current_arousal(0.0)
    , current_dominance(0.0)  {
    }
  EmotionalState_(const ContainerAllocator& _alloc)
    : from_emotional_state(_alloc)
    , to_emotional_state(_alloc)
    , current_pleasure(0.0)
    , current_arousal(0.0)
    , current_dominance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _from_emotional_state_type;
  _from_emotional_state_type from_emotional_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _to_emotional_state_type;
  _to_emotional_state_type to_emotional_state;

   typedef float _current_pleasure_type;
  _current_pleasure_type current_pleasure;

   typedef float _current_arousal_type;
  _current_arousal_type current_arousal;

   typedef float _current_dominance_type;
  _current_dominance_type current_dominance;





  typedef boost::shared_ptr< ::cyborg_controller::EmotionalState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyborg_controller::EmotionalState_<ContainerAllocator> const> ConstPtr;

}; // struct EmotionalState_

typedef ::cyborg_controller::EmotionalState_<std::allocator<void> > EmotionalState;

typedef boost::shared_ptr< ::cyborg_controller::EmotionalState > EmotionalStatePtr;
typedef boost::shared_ptr< ::cyborg_controller::EmotionalState const> EmotionalStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyborg_controller::EmotionalState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyborg_controller::EmotionalState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cyborg_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cyborg_controller': ['/home/lassegoncz/catkin_ws/src/cyborg_ros_controller/msg', '/home/lassegoncz/catkin_ws/devel/share/cyborg_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::EmotionalState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::EmotionalState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::EmotionalState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff5f086e373f1e982e89fbc9298d99be";
  }

  static const char* value(const ::cyborg_controller::EmotionalState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff5f086e373f1e98ULL;
  static const uint64_t static_value2 = 0x2e89fbc9298d99beULL;
};

template<class ContainerAllocator>
struct DataType< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyborg_controller/EmotionalState";
  }

  static const char* value(const ::cyborg_controller::EmotionalState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string from_emotional_state\n\
string to_emotional_state\n\
float32 current_pleasure\n\
float32 current_arousal\n\
float32 current_dominance\n\
";
  }

  static const char* value(const ::cyborg_controller::EmotionalState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from_emotional_state);
      stream.next(m.to_emotional_state);
      stream.next(m.current_pleasure);
      stream.next(m.current_arousal);
      stream.next(m.current_dominance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmotionalState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyborg_controller::EmotionalState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyborg_controller::EmotionalState_<ContainerAllocator>& v)
  {
    s << indent << "from_emotional_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.from_emotional_state);
    s << indent << "to_emotional_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.to_emotional_state);
    s << indent << "current_pleasure: ";
    Printer<float>::stream(s, indent + "  ", v.current_pleasure);
    s << indent << "current_arousal: ";
    Printer<float>::stream(s, indent + "  ", v.current_arousal);
    s << indent << "current_dominance: ";
    Printer<float>::stream(s, indent + "  ", v.current_dominance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBORG_CONTROLLER_MESSAGE_EMOTIONALSTATE_H
