// Generated by gencpp from file cyborg_controller/StateMachineFeedback.msg
// DO NOT EDIT!


#ifndef CYBORG_CONTROLLER_MESSAGE_STATEMACHINEFEEDBACK_H
#define CYBORG_CONTROLLER_MESSAGE_STATEMACHINEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyborg_controller
{
template <class ContainerAllocator>
struct StateMachineFeedback_
{
  typedef StateMachineFeedback_<ContainerAllocator> Type;

  StateMachineFeedback_()
    : status()
    , message()  {
    }
  StateMachineFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct StateMachineFeedback_

typedef ::cyborg_controller::StateMachineFeedback_<std::allocator<void> > StateMachineFeedback;

typedef boost::shared_ptr< ::cyborg_controller::StateMachineFeedback > StateMachineFeedbackPtr;
typedef boost::shared_ptr< ::cyborg_controller::StateMachineFeedback const> StateMachineFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cyborg_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cyborg_controller': ['/home/lassegoncz/catkin_ws/src/cyborg_ros_controller/msg', '/home/lassegoncz/catkin_ws/devel/share/cyborg_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7601b7c86f40485172dd55be09fb75e9";
  }

  static const char* value(const ::cyborg_controller::StateMachineFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7601b7c86f404851ULL;
  static const uint64_t static_value2 = 0x72dd55be09fb75e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyborg_controller/StateMachineFeedback";
  }

  static const char* value(const ::cyborg_controller::StateMachineFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
string status #optional\n\
string message #optional\n\
\n\
";
  }

  static const char* value(const ::cyborg_controller::StateMachineFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateMachineFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyborg_controller::StateMachineFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyborg_controller::StateMachineFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBORG_CONTROLLER_MESSAGE_STATEMACHINEFEEDBACK_H
