// Generated by gencpp from file cyborg_controller/StateMachineGoal.msg
// DO NOT EDIT!


#ifndef CYBORG_CONTROLLER_MESSAGE_STATEMACHINEGOAL_H
#define CYBORG_CONTROLLER_MESSAGE_STATEMACHINEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyborg_controller
{
template <class ContainerAllocator>
struct StateMachineGoal_
{
  typedef StateMachineGoal_<ContainerAllocator> Type;

  StateMachineGoal_()
    : previous_state()
    , event()
    , current_state()
    , order()  {
    }
  StateMachineGoal_(const ContainerAllocator& _alloc)
    : previous_state(_alloc)
    , event(_alloc)
    , current_state(_alloc)
    , order(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _previous_state_type;
  _previous_state_type previous_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type;
  _event_type event;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _current_state_type;
  _current_state_type current_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _order_type;
  _order_type order;





  typedef boost::shared_ptr< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> const> ConstPtr;

}; // struct StateMachineGoal_

typedef ::cyborg_controller::StateMachineGoal_<std::allocator<void> > StateMachineGoal;

typedef boost::shared_ptr< ::cyborg_controller::StateMachineGoal > StateMachineGoalPtr;
typedef boost::shared_ptr< ::cyborg_controller::StateMachineGoal const> StateMachineGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyborg_controller::StateMachineGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cyborg_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cyborg_controller': ['/home/lassegoncz/catkin_ws/src/cyborg_ros_controller/msg', '/home/lassegoncz/catkin_ws/devel/share/cyborg_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca0cbc617848fd96cc506786c47de76e";
  }

  static const char* value(const ::cyborg_controller::StateMachineGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca0cbc617848fd96ULL;
  static const uint64_t static_value2 = 0xcc506786c47de76eULL;
};

template<class ContainerAllocator>
struct DataType< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyborg_controller/StateMachineGoal";
  }

  static const char* value(const ::cyborg_controller::StateMachineGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string previous_state\n\
string event\n\
string current_state\n\
string order #valid is EXECUTE or CANCEL\n\
";
  }

  static const char* value(const ::cyborg_controller::StateMachineGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.previous_state);
      stream.next(m.event);
      stream.next(m.current_state);
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateMachineGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyborg_controller::StateMachineGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyborg_controller::StateMachineGoal_<ContainerAllocator>& v)
  {
    s << indent << "previous_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.previous_state);
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event);
    s << indent << "current_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.current_state);
    s << indent << "order: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBORG_CONTROLLER_MESSAGE_STATEMACHINEGOAL_H
