(cl:defpackage rosarnl-msg
  (:use )
  (:export
   "<BATTERYSTATUS>"
   "BATTERYSTATUS"
   "<BUMPERSTATE>"
   "BUMPERSTATE"
   "<JOGPOSITIONACTION>"
   "JOGPOSITIONACTION"
   "<JOGPOSITIONACTIONFEEDBACK>"
   "JOGPOSITIONACTIONFEEDBACK"
   "<JOGPOSITIONACTIONGOAL>"
   "JOGPOSITIONACTIONGOAL"
   "<JOGPOSITIONACTIONRESULT>"
   "JOGPOSITIONACTIONRESULT"
   "<JOGPOSITIONFEEDBACK>"
   "JOGPOSITIONFEEDBACK"
   "<JOGPOSITIONGOAL>"
   "JOGPOSITIONGOAL"
   "<JOGPOSITIONRESULT>"
   "JOGPOSITIONRESULT"
  ))

