; Auto-generated. Do not edit!


(cl:in-package rosarnl-msg)


;//! \htmlinclude JogPositionResult.msg.html

(cl:defclass <JogPositionResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JogPositionResult (<JogPositionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JogPositionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JogPositionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosarnl-msg:<JogPositionResult> is deprecated: use rosarnl-msg:JogPositionResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JogPositionResult>) ostream)
  "Serializes a message object of type '<JogPositionResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JogPositionResult>) istream)
  "Deserializes a message object of type '<JogPositionResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JogPositionResult>)))
  "Returns string type for a message object of type '<JogPositionResult>"
  "rosarnl/JogPositionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JogPositionResult)))
  "Returns string type for a message object of type 'JogPositionResult"
  "rosarnl/JogPositionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JogPositionResult>)))
  "Returns md5sum for a message object of type '<JogPositionResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JogPositionResult)))
  "Returns md5sum for a message object of type 'JogPositionResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JogPositionResult>)))
  "Returns full string definition for message of type '<JogPositionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no value provided with result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JogPositionResult)))
  "Returns full string definition for message of type 'JogPositionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no value provided with result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JogPositionResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JogPositionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JogPositionResult
))
