; Auto-generated. Do not edit!


(cl:in-package rosarnl-msg)


;//! \htmlinclude JogPositionGoal.msg.html

(cl:defclass <JogPositionGoal> (roslisp-msg-protocol:ros-message)
  ((offset
    :reader offset
    :initarg :offset
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D))
   (timeout
    :reader timeout
    :initarg :timeout
    :type cl:real
    :initform 0))
)

(cl:defclass JogPositionGoal (<JogPositionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JogPositionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JogPositionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosarnl-msg:<JogPositionGoal> is deprecated: use rosarnl-msg:JogPositionGoal instead.")))

(cl:ensure-generic-function 'offset-val :lambda-list '(m))
(cl:defmethod offset-val ((m <JogPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosarnl-msg:offset-val is deprecated.  Use rosarnl-msg:offset instead.")
  (offset m))

(cl:ensure-generic-function 'timeout-val :lambda-list '(m))
(cl:defmethod timeout-val ((m <JogPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosarnl-msg:timeout-val is deprecated.  Use rosarnl-msg:timeout instead.")
  (timeout m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JogPositionGoal>) ostream)
  "Serializes a message object of type '<JogPositionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'offset) ostream)
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'timeout)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'timeout) (cl:floor (cl:slot-value msg 'timeout)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JogPositionGoal>) istream)
  "Deserializes a message object of type '<JogPositionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'offset) istream)
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'timeout) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JogPositionGoal>)))
  "Returns string type for a message object of type '<JogPositionGoal>"
  "rosarnl/JogPositionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JogPositionGoal)))
  "Returns string type for a message object of type 'JogPositionGoal"
  "rosarnl/JogPositionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JogPositionGoal>)))
  "Returns md5sum for a message object of type '<JogPositionGoal>"
  "7800e2305f96351593150df12af52c22")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JogPositionGoal)))
  "Returns md5sum for a message object of type 'JogPositionGoal"
  "7800e2305f96351593150df12af52c22")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JogPositionGoal>)))
  "Returns full string definition for message of type '<JogPositionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal offset~%geometry_msgs/Pose2D offset~%duration timeout~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JogPositionGoal)))
  "Returns full string definition for message of type 'JogPositionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal offset~%geometry_msgs/Pose2D offset~%duration timeout~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JogPositionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'offset))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JogPositionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'JogPositionGoal
    (cl:cons ':offset (offset msg))
    (cl:cons ':timeout (timeout msg))
))
