; Auto-generated. Do not edit!


(cl:in-package rosarnl-msg)


;//! \htmlinclude JogPositionFeedback.msg.html

(cl:defclass <JogPositionFeedback> (roslisp-msg-protocol:ros-message)
  ((current
    :reader current
    :initarg :current
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D))
   (duration
    :reader duration
    :initarg :duration
    :type cl:real
    :initform 0))
)

(cl:defclass JogPositionFeedback (<JogPositionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JogPositionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JogPositionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosarnl-msg:<JogPositionFeedback> is deprecated: use rosarnl-msg:JogPositionFeedback instead.")))

(cl:ensure-generic-function 'current-val :lambda-list '(m))
(cl:defmethod current-val ((m <JogPositionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosarnl-msg:current-val is deprecated.  Use rosarnl-msg:current instead.")
  (current m))

(cl:ensure-generic-function 'duration-val :lambda-list '(m))
(cl:defmethod duration-val ((m <JogPositionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosarnl-msg:duration-val is deprecated.  Use rosarnl-msg:duration instead.")
  (duration m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JogPositionFeedback>) ostream)
  "Serializes a message object of type '<JogPositionFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current) ostream)
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'duration)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'duration) (cl:floor (cl:slot-value msg 'duration)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JogPositionFeedback>) istream)
  "Deserializes a message object of type '<JogPositionFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current) istream)
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'duration) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JogPositionFeedback>)))
  "Returns string type for a message object of type '<JogPositionFeedback>"
  "rosarnl/JogPositionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JogPositionFeedback)))
  "Returns string type for a message object of type 'JogPositionFeedback"
  "rosarnl/JogPositionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JogPositionFeedback>)))
  "Returns md5sum for a message object of type '<JogPositionFeedback>"
  "a3028aaede1352c7007b717c9afed53f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JogPositionFeedback)))
  "Returns md5sum for a message object of type 'JogPositionFeedback"
  "a3028aaede1352c7007b717c9afed53f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JogPositionFeedback>)))
  "Returns full string definition for message of type '<JogPositionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback, current pose and time since start of goal. TODO include remaining distannce~%geometry_msgs/Pose2D current~%duration duration~%~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JogPositionFeedback)))
  "Returns full string definition for message of type 'JogPositionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback, current pose and time since start of goal. TODO include remaining distannce~%geometry_msgs/Pose2D current~%duration duration~%~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JogPositionFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JogPositionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'JogPositionFeedback
    (cl:cons ':current (current msg))
    (cl:cons ':duration (duration msg))
))
