// Generated by gencpp from file cyborg_navigation/NavigationGoal.msg
// DO NOT EDIT!


#ifndef CYBORG_NAVIGATION_MESSAGE_NAVIGATIONGOAL_H
#define CYBORG_NAVIGATION_MESSAGE_NAVIGATIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyborg_navigation
{
template <class ContainerAllocator>
struct NavigationGoal_
{
  typedef NavigationGoal_<ContainerAllocator> Type;

  NavigationGoal_()
    : order()
    , location_name()  {
    }
  NavigationGoal_(const ContainerAllocator& _alloc)
    : order(_alloc)
    , location_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _order_type;
  _order_type order;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _location_name_type;
  _location_name_type location_name;





  typedef boost::shared_ptr< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationGoal_

typedef ::cyborg_navigation::NavigationGoal_<std::allocator<void> > NavigationGoal;

typedef boost::shared_ptr< ::cyborg_navigation::NavigationGoal > NavigationGoalPtr;
typedef boost::shared_ptr< ::cyborg_navigation::NavigationGoal const> NavigationGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyborg_navigation::NavigationGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cyborg_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'cyborg_navigation': ['/home/lassegoncz/catkin_ws/devel/share/cyborg_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76b28b03838801536ea3c48deea22ff4";
  }

  static const char* value(const ::cyborg_navigation::NavigationGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76b28b0383880153ULL;
  static const uint64_t static_value2 = 0x6ea3c48deea22ff4ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyborg_navigation/NavigationGoal";
  }

  static const char* value(const ::cyborg_navigation::NavigationGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string order\n\
string location_name\n\
";
  }

  static const char* value(const ::cyborg_navigation::NavigationGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
      stream.next(m.location_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyborg_navigation::NavigationGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyborg_navigation::NavigationGoal_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.order);
    s << indent << "location_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBORG_NAVIGATION_MESSAGE_NAVIGATIONGOAL_H
