(cl:defpackage cyborg_navigation-msg
  (:use )
  (:export
   "<NAVIGATIONACTION>"
   "NAVIGATIONACTION"
   "<NAVIGATIONACTIONFEEDBACK>"
   "NAVIGATIONACTIONFEEDBACK"
   "<NAVIGATIONACTIONGOAL>"
   "NAVIGATIONACTIONGOAL"
   "<NAVIGATIONACTIONRESULT>"
   "NAVIGATIONACTIONRESULT"
   "<NAVIGATIONFEEDBACK>"
   "NAVIGATIONFEEDBACK"
   "<NAVIGATIONGOAL>"
   "NAVIGATIONGOAL"
   "<NAVIGATIONRESULT>"
   "NAVIGATIONRESULT"
  ))

