(cl:defpackage cyborg_controller-msg
  (:use )
  (:export
   "<EMOTIONALFEEDBACK>"
   "EMOTIONALFEEDBACK"
   "<EMOTIONALSTATE>"
   "EMOTIONALSTATE"
   "<STATEMACHINEACTION>"
   "STATEMACHINEACTION"
   "<STATEMACHINEACTIONFEEDBACK>"
   "STATEMACHINEACTIONFEEDBACK"
   "<STATEMACHINEACTIONGOAL>"
   "STATEMACHINEACTIONGOAL"
   "<STATEMACHINEACTIONRESULT>"
   "STATEMACHINEACTIONRESULT"
   "<STATEMACHINEFEEDBACK>"
   "STATEMACHINEFEEDBACK"
   "<STATEMACHINEGOAL>"
   "STATEMACHINEGOAL"
   "<STATEMACHINERESULT>"
   "STATEMACHINERESULT"
   "<SYSTEMSTATE>"
   "SYSTEMSTATE"
  ))

