; Auto-generated. Do not edit!


(cl:in-package cyborg_controller-msg)


;//! \htmlinclude StateMachineFeedback.msg.html

(cl:defclass <StateMachineFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform "")
   (message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass StateMachineFeedback (<StateMachineFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StateMachineFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StateMachineFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cyborg_controller-msg:<StateMachineFeedback> is deprecated: use cyborg_controller-msg:StateMachineFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <StateMachineFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cyborg_controller-msg:status-val is deprecated.  Use cyborg_controller-msg:status instead.")
  (status m))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <StateMachineFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cyborg_controller-msg:message-val is deprecated.  Use cyborg_controller-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StateMachineFeedback>) ostream)
  "Serializes a message object of type '<StateMachineFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StateMachineFeedback>) istream)
  "Deserializes a message object of type '<StateMachineFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StateMachineFeedback>)))
  "Returns string type for a message object of type '<StateMachineFeedback>"
  "cyborg_controller/StateMachineFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StateMachineFeedback)))
  "Returns string type for a message object of type 'StateMachineFeedback"
  "cyborg_controller/StateMachineFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StateMachineFeedback>)))
  "Returns md5sum for a message object of type '<StateMachineFeedback>"
  "7601b7c86f40485172dd55be09fb75e9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StateMachineFeedback)))
  "Returns md5sum for a message object of type 'StateMachineFeedback"
  "7601b7c86f40485172dd55be09fb75e9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StateMachineFeedback>)))
  "Returns full string definition for message of type '<StateMachineFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string status #optional~%string message #optional~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StateMachineFeedback)))
  "Returns full string definition for message of type 'StateMachineFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string status #optional~%string message #optional~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StateMachineFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StateMachineFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StateMachineFeedback
    (cl:cons ':status (status msg))
    (cl:cons ':message (message msg))
))
