# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rosarnl/BatteryStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BatteryStatus(genpy.Message):
  _md5sum = "a5ae24af1ef085b1c28fd0c2d4869c5f"
  _type = "rosarnl/BatteryStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 CHARGING_UNKNOWN = -1
int8 CHARGING_NOT = 0
int8 CHARGING_BULK = 1
int8 CHARGING_OVERCHARGE = 2
int8 CHARGING_FLOAT = 3
int8 CHARGING_BALANCE = 4

int8 charging_state
float32 charge_percent
"""
  # Pseudo-constants
  CHARGING_UNKNOWN = -1
  CHARGING_NOT = 0
  CHARGING_BULK = 1
  CHARGING_OVERCHARGE = 2
  CHARGING_FLOAT = 3
  CHARGING_BALANCE = 4

  __slots__ = ['charging_state','charge_percent']
  _slot_types = ['int8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       charging_state,charge_percent

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BatteryStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.charging_state is None:
        self.charging_state = 0
      if self.charge_percent is None:
        self.charge_percent = 0.
    else:
      self.charging_state = 0
      self.charge_percent = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_bf().pack(_x.charging_state, _x.charge_percent))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.charging_state, _x.charge_percent,) = _get_struct_bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_bf().pack(_x.charging_state, _x.charge_percent))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.charging_state, _x.charge_percent,) = _get_struct_bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_bf = None
def _get_struct_bf():
    global _struct_bf
    if _struct_bf is None:
        _struct_bf = struct.Struct("<bf")
    return _struct_bf
